
# aws config
cloud:
  aws:
    credentials:
      access-key: AKIA57Y75DGUH2HM5OBX
      secret-key: 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
    endpointUrl: https://s3.us-east-2.amazonaws.com
    region:
      static: us-east-2
    stack:
      auto: false

#  spring bucket
application:
  bucket:
    name: aws-s3-uploading


# spring servlet
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
      file-size-threshold: 2MB


# server port
server:
  port: 9090
